### ISSUE TITLE
SEMCOL anomalies

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#14]
@ohAitch I believe I have the logic for 1-running hoons done.  Here is a list of anomalies, for addition `anomaly.suppressions`:
[semcol.lint.txt](https://github.com/jeffreykegler/yahc/files/2892255/semcol.lint.txt)
A lot of the anomalies are paired runsteps, And a lot of runsteps are indented to align with the head of the running, which I believe is incorrect.

I allow gaps with header comments.  Note that the comments in `gen/test.hoon` are incorrectly aligned for headers -- they align with the runsteps, not with the rune.

**Comment by ohAitch** [comment]
1. `gen/test` is an anomaly yup; earlier I considered distinguishing empty and non-empty header comments for purpose of determining run/jog alignment (and disallowing them in newline-equivalent gaps), but "headers always have to be outdented" seems more solid.

2. The two `output ;: weld`s are doing annotational indentation, agree that those should just be split onto the following line(and the `?-  i.ovr` queensided accordingly)

3. The next two welds are doing kingside jogging with clear purpose; probably just whitelist `;:` for allowing jogging indentation despite technically being a running rune? (I guess just allowing jogging in all running runes wouldn't be the worst, sometimes a list just is consecutive pairs; idk how hairy kingside jogging vs queenside jogging vs regular running discrimination would be)

4. It would be nice for the hoon.hoon weld to have a blank header before the last(multiline) element; not sure to what extent this is the purview of indentation linting :P (+1 on the one-space misindent it's actually complaining about)

5. drum gh/issues gh/issue-comment dill "overindented"s are spot on; the zuse ones could stand to chill, having arbitrarily many elements on the first line seems fine

6. not sure what to do with hall-json, the suggested "move to next line" is probably fine but not great.
For the warning itself(and equivalent zuse ones), probably best to consolidate "should be on next line outdented by x" instead of doubled "wrong line" and "outdent this"? Esp in cases where outdenting on the same line would clearly not work due to there being code in the way

**Comment by jeffreykegler** [comment]
@ohAitch -- I created a new suppressions file `later.suppressions` for all the `weld`-related issues.  This is for "kicking the can down the road".  I intend that all the suppressions in `later.suppressions` will be "un-suppressed" before we file PR's against the `arvo/` codebase.

My reason for postponing action on the `weld`-related issues is that I wanted to perfect the logic for joggning and running hoons first, then annotations.  A problem is that one or two 1-running hoons (SEMCOL and maybe SEMSIG) are also annotations.  With `later.suppressions` I can leave the annotation part of the task for later.

Also, I fixed the logic for 1-running to allow the running to contain an initial line with any number of 1-stop-separated runsteps.

**Comment by jeffreykegler** [comment]
@ohAitch -- I have updated the whitespace doc to allow multiple runstops on the 1st line of the running of a 1-running hoon.

And I added the warnings indicated in your last comment to `anomaly.suppressions`.  With this I believe this issue is complete.

**Comment by jeffreykegler** [comment]
Closed as per the above.
