### ISSUE TITLE
LUTE status

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#25]
Here is the lint output for `lute`'s, which will be the basis of comments to follow.

[lute.lint.txt](https://github.com/jeffreykegler/yahc/files/3024855/lute.lint.txt)

**Comment by jeffreykegler** [comment]
There is a kind of pattern to the whitespace, but it looks awfully like it might be special to this case.  I wonder if I should just leave `lute`'s totally "free form" -- no lint warnings, except perhaps for problematic interior comments?

@ohAitch -- what do you think?

**Comment by ohAitch** [comment]
Lute is the weird tall-form `[]` right? Not enforcing whitespace seems reasonable yup, I think its main use is going to be this kind of "we're not using normal irregular :* because we wanted to align things"; and multiline nock literals, which will want to be indented according to the nock operators which show up as "freeform" extra indents e.g.

```
[ %6  [%3 %0 1]
    [%1 0]
  [%0 2]
]
```

Besides interior comments, "the `[` and `]` are either on the same line or same column, and in the latter case contents are indented past that parent column" might be good?

**Comment by jeffreykegler** [comment]
Will do.  Since the multiline form has no examples in the `arvo/` corpus, I may continue to treat it as NYI, with a comment in the code as to what you wanted done for when the case comes up.

I will mark this as my task and then, assuming I have no further questions, mark it "ready to close"

**Comment by jeffreykegler** [comment]
I have implemented lutes, and updated [the whitespace doc](https://github.com/jeffreykegler/yahc/blob/master/misc/whitespace.md. accordingly.  One-line lutes are free-form, multi-line lutes (of which `arvo/` contains no examples) will cause a "not yet implemented" warning.

I will mark this "ready for closing", and if nothing comes up, close it shortly.

**Comment by jeffreykegler** [comment]
Closed as per the above.
