### ISSUE TITLE
"Other" wuthep kingside lint warnings

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#7]
[other_wuthep_kingside.txt](https://github.com/jeffreykegler/yahc/files/2848040/other_wuthep_kingside.txt)

@ohAitch Here is a list of WUTHEP kingside hoonlint warnings not pulled out for special treatment.
My suggestion is that you skim these just in case there remain some usages you want to be considered "acceptable".  If there are none, I will add all of these to the anomalies list.

**Comment by ohAitch** [comment]
dojo - yep  
hall, capitalize, more hall - looks like there's a convention of "kingside, empty comment line, queenside"? it's like 5 occurences total so just kill it yeah  
&nbsp;- I will note that the "underindented by 2" errors are not great, I get that this is a line that will need to be touched, but locally it's the correct thing; will probably be more clear with combined message contexts though  
static - should be queenside instead of indented 2 stops, but yeah as discussed  
help - uhh, aligned, but I see the point. probably just indent 24 (really anomalies.list should be cleanup.patch, but that can come in the future)  
helm - yep  
womb - nice catch!  
hoon - compiler jogs, referents, heads - all look like good fixes  
clay %tabl - oof. I see what it's doing, and am probably responsible; fix it yeah(also %tabl is gone in 2019 iirc)  
clay ++execute-changes - should be queenside  
clay ++read-at-aeon - uh, split kingside as suggested is reasonable yeah  
gall - yep! (similarly 343/344 should be aligned)  
&nbsp;- tho 653 is only overindented by like, 1 space

**Comment by jeffreykegler** [comment]
What I call `anomaly.suppression` is (as I plan things) the input for "cleanup.patch".  My current plan of action is

1. Silence all warnings in the lint output for arvo/ either through fixing hoonlint to accept the code; adding the warning to `anomaly.suppression`; or adding the warning to the (less temporary) `arvo.suppressions` suppression file.
2. Convert `hoonfmt `(renamed from hoontidy to be consistent with Curtis's terminology) to follow the identation standards discovered in the process of doing step 1.
3. Convert `hoonfmt` to honor suppression files -- `hoonfmt` will not rewrite the code to fix "suppressed" problems.
4. Run `hoonfmt` with `arvo.suppressions` but **without** `anomaly.suppressions`.  That way all and only the anomalies in `anomaly.suppressions` should be changed in the `hoonfmt` output.
5. Use the `hoonfmt` output from step 4. to generate a patch to the arvo/ codebase.  It think this patch is equivalent to what you mean by `cleanup.patch`.  This can be submitted as a (big!) PR to the arvo/ repository.

Make sense?  I may alter the above plan in detail, but that's my general strategic direction.

**Comment by ohAitch** [comment]
Yup, that sounds like exactly the way I was expecting it to come in the
future!

**Comment by jeffreykegler** [comment]
I read all your yes's in your comment-before-last as "Yes, go ahead and add these all to `anomaly.suppressions`, with appropriate comments, including a reference back to this issue".  Unless I head otherwise, I will do that and then close this ticket.

**Comment by jeffreykegler** [comment]
Closed as per the above.
