### ISSUE TITLE
Wuthep queenside lint warnings

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#8]
@ohAitch I think that all of these are candidates for addition to `anomaly.suppression`.  Let me know where you disagree.

[wuthep_queen_anom.txt](https://github.com/jeffreykegler/yahc/files/2849182/wuthep_queen_anom.txt)

**Comment by jeffreykegler** [comment]
Also, the lint output for this illustrates my fix of issue #5 .

**Comment by ohAitch** [comment]
Yup those look great! Maybe I'd swap the "underindented by 2" to the beginning of the line and filename/line/column to the end, as those are implicit from the ==, following line, or relatively unambiguous respectively.

[hoon.hoon 7883:9](https://github.com/urbit/arvo/blob/7610c12/sys/hoon.hoon#L7883) "overindented by 1" is particularly delightful (and 100% accurate)

The [hoon.hoon 8880 joined children](https://github.com/urbit/arvo/blob/7610c12/sys/hoon.hoon#L7883) seem consistently indented by 3 spaces instead of 2, I wonder if this is related to the inconsistent indent by 3 spaces in other places?

[gall ++load](https://github.com/urbit/arvo/blob/7610c12/sys/vane/gall.hoon#L1298) probably just wants to be kingside? Agree that it's an anomaly at any rate

**Comment by jeffreykegler** [comment]
The initial "fileName line:column type" is the same as the suppression and inclusion file format, and by using hoonlint's output (sometimes with a bit of editing) as suppression and inclusion files I can accomplish a lot of trickery.  So, yes, from a human POV putting that stuff at the beginning is sometimes annoying -- forcing the eye to scan a bit to find what it really is looking for.  But right now, that format is saving me **lots** of time.

**Comment by ohAitch** [comment]
I mean yeah I just swapped them around in a text editor, it's nbd. And having the error message last lets you e.g. use semicolons in the message itself slightly more freely.

**Comment by jeffreykegler** [comment]
@ohAitch -- I think the `anomaly.suppressions` as of the above reference commit takes care of this.  Unless I hear otherwise, I will close this issue shortly.

**Comment by jeffreykegler** [comment]
Closed for the reason given in the previous comment.
